### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by ottenhoff** [rsf/RSFUtil#4]
Found in Sakai via Mailtool with a huge course ( > 1000 users):

15-Mar-2017 13:07:55.599 WARN [http-apr-8344-exec-353] PonderUtilCore.handle Error invoking action
Target exception of class java.lang.StackOverflowError
Successive lines until stack trace show causes progressing to exception site:

java.lang.StackOverflowError
        at uk.org.ponder.rsf.request.SVESorter.scheduleWrites(SVESorter.java:141)
        at uk.org.ponder.rsf.request.SVESorter.scheduleWrites(SVESorter.java:141)
        at uk.org.ponder.rsf.request.SVESorter.attemptEvaluate(SVESorter.java:125)                                                                                                                                                       at uk.org.ponder.rsf.request.SVESorter.scheduleWrites(SVESorter.java:148)

**Comment by axxter99** [comment]
https://github.com/rsf/rsf : rsf/rsf-core/core/src/uk/org/ponder/rsf/request/SVESorter.java
